version: 2
jobs:
  build:
    docker:
      - image: google/cloud-sdk

    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Install dependencies
          command: |
            echo $GCLOUD_SERVICE_KEY
            apt-get update
            apt-get install -y gettext

      - run:
          name: Auth Google Cloud k8s
          command: |
            echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
            gcloud auth configure-docker
            gcloud container clusters get-credentials gymio-cluster

      - run:
          name: Build Docker
          command: |
            docker build \
              -t gcr.io/gymio-220023/$CIRCLE_PROJECT_REPONAME:$CIRCLE_PROJECT_USERNAME-$CIRCLE_BRANCH \
              -t gcr.io/gymio-220023/$CIRCLE_PROJECT_REPONAME:$CIRCLE_PROJECT_USERNAME-$CIRCLE_BRANCH-$CIRCLE_SHA1 \
              -f build/Dockerfile \
              .
            docker push gcr.io/gymio-220023/$CIRCLE_PROJECT_REPONAME:$CIRCLE_PROJECT_USERNAME-$CIRCLE_BRANCH-$CIRCLE_SHA1
            docker push gcr.io/gymio-220023/$CIRCLE_PROJECT_REPONAME:$CIRCLE_PROJECT_USERNAME-$CIRCLE_BRANCH

      - run:
          name: Deploy to k8s
          command: |
            # Provision
            envsubst < deployment/gymio-deployment.yaml > deployment/gymio-deployment-rendered.yaml
            echo $GYMIO_DB_SERVICE_ACCOUNT > ${HOME}/gcloud-gymio-db-service-key.json

            # Create secrets
            kubectl delete secret cloudsql-instance-credentials --ignore-not-found
            kubectl create secret generic cloudsql-instance-credentials \
              --from-file=credentials.json=${HOME}/gcloud-gymio-db-service-key.json

            kubectl delete secret cloudsql-db-credentials --ignore-not-found
            kubectl create secret generic cloudsql-db-credentials \
              --from-literal=username="$GYMIO_DB_USER" --from-literal=password="$GYMIO_DB_PASSWORD"

            # Deployment and service
            kubectl apply -f deployment/gymio-deployment-rendered.yaml
            kubectl apply -f deployment/gymio-service.yaml

